sudo: false
language: ruby
rvm:
  - 2.5.1
services:
  - postgresql
before_install: gem install bundler -v "$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)"
before_script:
  - bundle install --jobs=3 --retry=3
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
script:
  - bundle exec rake test
